---
  env:
    browser: true
    node: true
  extends: airbnb
  rules:
    no-console: 0
    arrow-body-style: 0
    no-param-reassign: 0
    no-shadow: 0
    object-curly-newline: 0
    react/no-this-in-sfc: 0
    max-len: 0
